#!/bin/bash

#Update nginx config to reference the policy
cat <<EOF >conf.d/default.conf
app_protect_enable on;
app_protect_security_log_enable on;
app_protect_security_log "/etc/app_protect/conf/log_default.json" /var/log/app_protect/security.log;
app_protect_policy_file /etc/app_protect/conf/$(echo $1 | sed 's/.*\///');
server {
    listen       80 default_server;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}

    # enable /api/ location with appropriate access control in order
    # to make use of NGINX Plus API
    #
    location /api/ {
        api write=on;
        allow all;
    #    allow 127.0.0.1;
    #    deny all;
    }

    # enable NGINX Plus Dashboard; requires /api/ location to be
    # enabled and appropriate access control for remote access
    #
    #location = /dashboard.html {
    #    root /usr/share/nginx/html;
    #}
}
EOF

kubectl create configmap config --from-file=$1 --from-file=./conf.d/default.conf --dry-run=client -o yaml -n nginx-plus | kubectl replace -f -

#Apply the updated Deployment manifest
kubectl apply  -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-protect
  namespace: nginx-plus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-protect
  template:
    metadata:
      labels:
        app: app-protect
        app.kubernetes.io/name: app-protect
    spec:
      containers:
      - image: localhost:5000/app-protect-converter:latest
        imagePullPolicy: IfNotPresent
        name: app-protect
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/license.jwt
          subPath: license.jwt
          name: license-token
        - mountPath: /etc/app_protect/conf/$(echo $1 | sed 's/.*\///')
          subPath: $(echo $1 | sed 's/.*\///')
          name: config
        - mountPath: /etc/nginx/conf.d/
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: nginx-plus
      serviceAccountName: nginx-plus
      volumes:
      - name: license-token
        secret:
          secretName: license-token
      - name: config
        configMap:
          name: config
EOF
