apiVersion: apps/v1
kind: Deployment
metadata:
  name: juicebox-deployment
  labels:
    app: juicebox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juicebox
  template:
    metadata:
      labels:
        app: juicebox
    spec:
      containers:
      - name: juicebox
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juicebox-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: juicebox
