apiVersion: v1
kind: Service
metadata:
  name: ext-authz
  namespace: f5-waf
spec:
  selector:
    app: ext-authz
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-authz
  namespace: f5-waf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz
  template:
    metadata:
      labels:
        app: ext-authz
        sidecar.istio.io/inject: "false" #do not inject the sidecar
    spec:
      containers:
        - name: ext-authz
          image: localhost:5000/flask-authorizer:latest
          ports:
            - containerPort: 9000
